from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from config.settings import get_settings
from schemas.analysis import AnalysisResult


class ReportGenerator:
    def __init__(self) -> None:
        self.settings = get_settings()

    def generate(self, result: AnalysisResult) -> Path:
        self.settings.report_dir.mkdir(parents=True, exist_ok=True)
        report_path = (self.settings.report_dir / f"{result.id}.pdf").resolve()

        document = SimpleDocTemplate(str(report_path), pagesize=letter, title="TruthLens AI Report")
        styles = getSampleStyleSheet()
        story = [
            Paragraph("TruthLens AI Authenticity Report", styles["Title"]),
            Spacer(1, 18),
            Paragraph("Generated by the TruthLens AI deepfake video analysis pipeline.", styles["BodyText"]),
            Spacer(1, 18),
        ]

        table_data = [
            ["File Name", result.file_name],
            ["Analysis Date", result.analyzed_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
            ["Result", result.result],
            ["Confidence", f"{result.confidence_score:.2f}%"],
            ["Manipulation Probability", f"{result.manipulation_probability:.2f}%"],
            ["Frames Analyzed", str(result.frames_analyzed)],
            ["Model", result.model_name],
            ["Recommendation", result.recommendation],
        ]
        table = Table(table_data, colWidths=[170, 340])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0B1220")),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                    ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#111827")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("PADDING", (0, 0), (-1, -1), 10),
                ]
            )
        )
        story.append(table)
        document.build(story)
        return report_path


report_generator = ReportGenerator()

