"""
PDF report generation service.

Produces a branded ReportLab PDF document summarising an analysis result.
The report is written to the configured report_dir and its path is stored
in the JobStore for download via GET /report/{id}.

Sprint 6: When cloud storage is introduced, upload the generated PDF to the
          storage service immediately after build() and return a presigned URL
          instead of a local Path. The generate() signature remains the same
          (returns a Path or URL string — callers use it opaquely).
Sprint 8: Add an organisation logo, watermark, and custom colour scheme for
          white-label deployments once multi-tenancy is implemented.
"""

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from config.settings import get_settings
from schemas.analysis import AnalysisResult

# Column widths for the data table (points). Total ≈ 510pt ≈ 7.08 inches —
# fits within the letter page width with default margins.
_LABEL_COL_WIDTH = 170
_VALUE_COL_WIDTH = 340

# Brand colours (match the frontend design system).
_BRAND_DARK = colors.HexColor("#0B1220")
_BRAND_TEXT = colors.HexColor("#111827")
_GRID_COLOR = colors.HexColor("#CBD5E1")


class ReportGenerator:
    """
    Builds a PDF authenticity report for a completed analysis job.

    Each call to generate() writes one PDF file to the configured report_dir.
    The service is stateless and thread-safe — multiple concurrent calls
    write to different file paths (keyed by result.id) without conflict.
    """

    def __init__(self) -> None:
        self.settings = get_settings()

    def generate(self, result: AnalysisResult) -> Path:
        """
        Build and write the PDF report for ``result``.

        Args:
            result: Completed AnalysisResult from the inference pipeline.

        Returns:
            Absolute Path to the written PDF file.

        Raises:
            OSError: If the report directory cannot be created or the file
                     cannot be written (e.g., disk full).
        """
        import tempfile
        import os
        
        # Create a secure temporary directory inside the OS's temp folder.
        # This prevents reports from persisting if not manually cleaned up.
        report_dir = Path(tempfile.mkdtemp(prefix="truthlens_reports_"))
        report_path = (report_dir / f"{result.id}.pdf").resolve()

        document = SimpleDocTemplate(
            str(report_path),
            pagesize=letter,
            title=f"TruthLens AI Report - {result.id}",
            author="TruthLens AI",
            topMargin=40,
            bottomMargin=40,
            leftMargin=40,
            rightMargin=40
        )
        styles = getSampleStyleSheet()
        
        # Define premium typography styles
        from reportlab.lib.styles import ParagraphStyle
        
        title_style = ParagraphStyle(
            'PremiumTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            textColor=_BRAND_DARK,
            spaceAfter=20,
            alignment=0 # Left
        )
        
        body_style = ParagraphStyle(
            'PremiumBody',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=11,
            textColor=_BRAND_TEXT,
            leading=16,
            spaceAfter=14
        )
        
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['BodyText'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            textColor=colors.gray,
            leading=12,
            spaceBefore=30,
            alignment=1 # Center
        )

        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=8,
            textColor=colors.HexColor("#9CA3AF"),
            alignment=1
        )

        story = [
            Paragraph("TRUTHLENS AI", ParagraphStyle('Brand', parent=title_style, fontSize=12, textColor=colors.gray, spaceAfter=5, tracking=2)),
            Paragraph("Forensic Analysis Report", title_style),
            Paragraph(
                f"Generated by the TruthLens AI multi-stage deepfake detection engine on {result.analyzed_at.strftime('%B %d, %Y at %H:%M:%S UTC')}.",
                body_style,
            ),
            Spacer(1, 15),
            self._build_table(result),
            Spacer(1, 25),
            Paragraph(
                "DISCLAIMER: This report reflects the statistical output of an automated artificial intelligence system. "
                "While TruthLens AI utilizes advanced neural networks and physics-based heuristics, it does not replace "
                "professional human forensic analysis. This document should be reviewed by a qualified analyst before being "
                "used for high-stakes decisions.",
                disclaimer_style,
            ),
            Spacer(1, 10),
            Paragraph(f"TruthLens AI v{self.settings.app_version} | Job ID: {result.id}", footer_style)
        ]

        document.build(story)
        return report_path

    def _build_table(self, result: AnalysisResult) -> Table:
        """Build the multi-section data table that forms the body of the report."""
        
        # 1. Executive Summary & Verdict
        table_data = [
            ["Job ID", result.id],
            ["File Name", result.file_name],
            ["Analysis Date", result.analyzed_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
            ["Risk Level", result.risk_level],
            ["Result", result.result],
            ["Overall Confidence", f"{result.confidence_score:.2f}%"],
            ["AI Model Confidence", f"{result.ai_confidence:.2f}%"],
            ["Heuristic Confidence", f"{result.heuristic_confidence:.2f}%"],
            ["Executive Summary", Paragraph(result.executive_summary)],
            ["Recommendation", Paragraph(result.recommendation)],
        ]
        
        # 2. Technical Metrics
        table_data.append(["-- TECHNICAL METRICS --", ""])
        for k, v in result.technical_metrics.items():
            table_data.append([k.replace("_", " ").title(), str(v)])

        # 3. Evidence Breakdown
        table_data.append(["-- EVIDENCE BREAKDOWN --", ""])
        for ev in result.evidence_breakdown:
            table_data.append([ev.title, Paragraph(f"Score: {ev.score:.2f} ({ev.status.upper()})<br/>{ev.explanation}")])

        # 4. Processing Stats
        table_data.append(["-- PROCESSING DETAILS --", ""])
        table_data.append(["Frames Analyzed", str(result.frames_analyzed)])
        table_data.append(["Processing Time", f"{result.analysis_time_seconds:.2f}s"])
        table_data.append(["Model", result.model_name])
        for k, v in result.model_information.items():
            table_data.append([f"Model {k.title()}", str(v)])
        
        table_data.append(["Forensic Notes", Paragraph(result.forensic_notes)])

        table = Table(table_data, colWidths=[_LABEL_COL_WIDTH, _VALUE_COL_WIDTH])
        
        style = TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), _BRAND_DARK),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("TEXTCOLOR", (1, 0), (1, -1), _BRAND_TEXT),
            ("GRID", (0, 0), (-1, -1), 0.5, _GRID_COLOR),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 10),
        ])
        
        # Style the section headers
        for i, row in enumerate(table_data):
            if row[0].startswith("-- "):
                style.add("BACKGROUND", (0, i), (-1, i), colors.HexColor("#1F2937"))
                style.add("TEXTCOLOR", (0, i), (-1, i), colors.white)
                style.add("SPAN", (0, i), (-1, i))
                style.add("ALIGN", (0, i), (-1, i), "CENTER")
                style.add("FONTNAME", (0, i), (-1, i), "Helvetica-Bold")
                
        table.setStyle(style)
        return table


# Module-level singleton.
report_generator = ReportGenerator()
