ALTER TABLE user_preferences
ADD COLUMN IF NOT EXISTS pomodoro_duration INTEGER DEFAULT 25,
ADD COLUMN IF NOT EXISTS short_break_duration INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS long_break_duration INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS work_start_time TEXT DEFAULT '09:00',
ADD COLUMN IF NOT EXISTS work_end_time TEXT DEFAULT '17:00',
ADD COLUMN IF NOT EXISTS auto_reflow BOOLEAN DEFAULT true;
